server:
  port: 1212
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/airbnb
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

app:
  jwt:
    secret: Airbnb&Java12
