server:
    port: 1212
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/figma
        username: postgres
        password: Urmat0204

    jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        open-in-view: false

app:
    jwt:
        secret: Airbnb&Java12
